## Baysian Classification Algorithm
### Name: Atharv Satish Nikam
### Roll No: PA-10

In [1]:
import numpy as np
import pandas as pd

### Iris Dataset

In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Gaussian naive bayes classification

In [8]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [10]:
#training
gnb.fit(df, iris.target)

GaussianNB()

In [11]:
#testing
pr = gnb.predict([[5.9, 3.0, 5.1, 1.8]])
pr

array([2])

## Multinomial naive bayes classification

In [2]:
from sklearn.feature_extraction import DictVectorizer

data = [
    {'house': 100, 'street': 50, 'shop': 25, 'car': 100, 'tree': 20}, #1
    {'house': 5, 'street': 5, 'shop': 0, 'car': 10, 'tree': 50, 'river':1}, #0
]

dv = DictVectorizer(sparse=False)
X = dv.fit_transform(data) # features
Y = np.array([1,0]) #calss labels
X

array([[100., 100.,   0.,  25.,  50.,  20.],
       [ 10.,   5.,   1.,   0.,   5.,  50.]])

In [5]:
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()

In [6]:
mnb.fit(X, Y) #training

MultinomialNB()

In [7]:
#ttesting
test_data = data = [{'house':80, 'street': 20, 'shop':15, 'car':70, 'tree':10, 'river':1},]

In [8]:
#prediction
pr = mnb.predict(dv.fit_transform(test_data))
pr

array([1])

## Text data (news data) classification using Multinomial NB

In [11]:
from sklearn.datasets import fetch_20newsgroups
data = fetch_20newsgroups()
data.target_names #class labels

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [12]:
train = fetch_20newsgroups(subset='train')
test = fetch_20newsgroups(subset='test')

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer #to convert into numeric form
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

model = make_pipeline(TfidfVectorizer(), MultinomialNB())

In [15]:
model.fit(train.data, train.target) #training
labels = model.predict(test.data) #testing

In [16]:
from sklearn.metrics import accuracy_score #accuracy
accuracy_score(test.target, labels)

0.7738980350504514

In [17]:
#prediction
pred = model.predict(["Hello the CD ROM is compact"])
pred

array([3])